#!/usr/bin/env bash

# basic but sufficient

COMPILER_ARGS=""
if [[ $1 == "release" ]]; then
	COMPILER_ARGS="-O -release"
fi

PREFIX="oleo_"


COMPILER="dmd"
if type ldc > /dev/null 2>&1; then
	COMPILER="ldc"
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR

mkdir -p bin

cd src

source_files=$(ls *.d)

cd ..

for file in $source_files; do
	in_file="src/$file"
	out_file="bin/$PREFIX${file%??}"
	
	$COMPILER $in_file -of=$out_file $COMPILER_ARGS
	
	rm $out_file".o"
done